// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_status_of_ContactDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_status_of_ContactDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201609190714118_fix_status_of_ContactDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
